In [1]:
import numpy as np

In [6]:
my_list=[1,2,3,4,5,0,7,8]
print(my_list)

[1, 2, 3, 4, 5, 0, 7, 8]


In [7]:
arr_1=np.array(my_list, dtype=int)

In [8]:
print(arr_1)

[1 2 3 4 5 0 7 8]


In [10]:
###todays assignment###

In [13]:
import numpy as np


my_array = np.array([[3, 2, 1], [4, 5, 6], [9, 8, 7]])


reversed_array = np.flip(my_array, axis=1)

print(reversed_array)


[[1 2 3]
 [6 5 4]
 [7 8 9]]


In [2]:
rows, cols = 3, 4

random_array = np.random.uniform(5, 10, size=(rows, cols))

print(random_array)


[[7.12081665 6.54191752 7.31507793 5.84066212]
 [7.72515033 7.63473287 6.41323158 6.49814588]
 [6.34829106 5.09918989 6.51779754 9.95987029]]


In [18]:
my_array = np.array([10, 20, 30, 40, 50])

p25 = np.percentile(my_array, 25)
median = np.percentile(my_array, 50)
p75 = np.percentile(my_array, 75)

print(f"25th percentile: {p25:.2f}")
print(f"Median (50th percentile): {median:.2f}")
print(f"75th percentile: {p75:.2f}")


25th percentile: 20.00
Median (50th percentile): 30.00
75th percentile: 40.00


In [4]:
import numpy as np


data = np.array([1, 2, 3, 5, np.nan, 7, 8, 9, 10])

# Find the positions of missing values
missing_indices = np.where(np.isnan(data))

# Print the positions of missing values
print("Positions of missing  values:", missing_indices)


Positions of missing  values: (array([4], dtype=int64),)


In [28]:
array = np.array([[10, 8, 4],
                  [6, 5, 2],
                  [9, 4, 7]])


column_index = 1  


sorted_indices = np.argsort(array[:, column_index])


sorted_array = array[sorted_indices]

print("Original array:")
print(array)

print("\nSorted array by column:")
print(sorted_array)

Original array:
[[10  8  4]
 [ 6  5  2]
 [ 9  4  7]]

Sorted array by column:
[[ 9  4  7]
 [ 6  5  2]
 [10  8  4]]


In [29]:
my_array = np.array([1, 2, 3, 1, 2, 1, 1, 1, 3, 2, 2, 1])


counts = np.bincount(my_array)


most_frequent_value = np.argmax(counts)

print(f"The most frequent value is: {most_frequent_value}")


The most frequent value is: 1


In [42]:
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Flatten the 2D array using faltten function()
flat_array = my_array.flatten()
print("Flattened array (using flatten()):")
print(flat_array)


Flattened array (using flatten()):
[1 2 3 4 5 6 7 8 9]


In [33]:
data = np.array([10, 20, 30, 40, 50])

#  mean
mean_value = np.mean(data)
print(f"Mean: {mean_value:.2f}")

#median
median_value = np.median(data)
print(f"Median: {median_value:.2f}")

# sd

std_value = np.std(data)
print(f"Standard Deviation: {std_value:.2f}")


Mean: 30.00
Median: 30.00
Standard Deviation: 14.14


In [37]:
point1 = np.array([1, 2, 3])
point2 = np.array([4, 5, 6])

# Euclidean distance
euclidean_distance = np.linalg.norm(point1 - point2)
print(f"Euclidean Distance: {euclidean_distance:.2f}")

# Manhaten distance 

manhattan_distance = np.sum(np.abs(point1 - point2))
print(f"Manhattan Distance: {manhattan_distance:.2f}")



Euclidean Distance: 5.20
Manhattan Distance: 9.00
